{{/*
generates ExternalSecret resources for each secret name found in the secretEnvs list
*/}}
{{- range $secret := .Values.externalSecretsEnvs }}
{{- if $.Capabilities.APIVersions.Has "external-secrets.io/v1" }}
apiVersion: external-secrets.io/v1
{{- else }}
apiVersion: external-secrets.io/v1beta1
{{- end }}
kind: ExternalSecret
metadata:
  name: {{ include "addSuffix" (dict "value" $secret.name "suffix" "-es") }}
  namespace: {{ $.Release.Namespace }}
spec:
  refreshInterval: {{ $secret.refreshInterval }}
  secretStoreRef:
    kind: ClusterSecretStore
    name: {{ $secret.storeName }}
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: {{ $secret.name }}
  dataFrom:
  - extract:
      conversionStrategy: Default
      decodingStrategy: None
      key: {{ $secret.key }}
      metadataPolicy: None
      version: AWSCURRENT
---
{{- end }}
