apiVersion: batch/v1
kind: CronJob
metadata:
  name: "gh-actions-runner-listener-pod-delete-cronjob"
spec:
  schedule: "{{ .Values.listenerPodDeleteCronJob.schedule }}"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: "{{ .Values.serviceAccount.name }}"
          containers:
            - name: "gh-actions-runner-listener-pod-delete-cronjob-container"
              image: "{{ .Values.listenerPodDeleteCronJob.image.registry }}/{{ .Values.listenerPodDeleteCronJob.image.repository }}:{{ .Values.listenerPodDeleteCronJob.image.tag }}"
              imagePullPolicy: "{{ .Values.listenerPodDeleteCronJob.image.pullPolicy }}"
              command:
                - /bin/bash
                - -c
                - |-
                  POD_STATES=$(kubectl -n {{ .Release.Namespace }} get pod | grep listener | awk '{print $1";"$3}')
                  echo "$POD_STATES" | while IFS= read -r PS; do
                    NAME=$(echo $PS | awk -F ';' '{print $1}')
                    STATUS=$(echo $PS | awk -F ';' '{print $2}')
                    if [ "$STATUS" = "Error" ]; then
                      kubectl -n {{ .Release.Namespace }} delete pod $NAME
                    fi
                  done
                  curl -Ss --max-time 5 -X POST http://localhost:15020/quitquitquit || true
          restartPolicy: Never
